const ADMIN_OVERRIDE_KEY = window.HOMESTEAD_ADMIN_META?.key || "homestead_admin_overrides";
const DEFAULT_CONFIG = window.HOMESTEAD_DEFAULT_CONFIG || {};
let siteConfig = JSON.parse(JSON.stringify(DEFAULT_CONFIG));
let currentLang = localStorage.getItem("preferred_lang") || (typeof navigator !== "undefined" && String(navigator.language || "").toLowerCase().startsWith("ko") ? "ko" : "en");
let activeRoomFilter = "all";
let isDrawerOpen = false;
let lastFocusedElement = null;
let heroCarouselTimer = null;
let heroSlideIndex = 0;

function clone(value) { return JSON.parse(JSON.stringify(value || {})); }
function isObject(value) { return value && typeof value === "object" && !Array.isArray(value); }
function deepMerge(base, override) { if (Array.isArray(override)) return override.map((item) => clone(item)); if (!isObject(override)) return override === undefined ? base : override; const result = isObject(base) ? { ...base } : {}; Object.entries(override).forEach(([key, value]) => { if (Array.isArray(value)) result[key] = value.map((item) => clone(item)); else if (isObject(value)) result[key] = deepMerge(result[key], value); else result[key] = value; }); return result; }
function escapeHtml(value) { return String(value || "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;"); }
function getCurrentCopy() { return siteConfig.pages?.[currentLang] || siteConfig.pages?.ko || {}; }
function getBrandTitle() { return currentLang === "ko" ? siteConfig.branding.ko : siteConfig.branding.en; }
function getBrandSubtitle() { return currentLang === "ko" ? siteConfig.branding.subtitleKo : siteConfig.branding.subtitleEn; }
function normalizeHeroImages(images) { const list = Array.isArray(images) ? images.map((item) => String(item || "").trim()).filter(Boolean) : []; if (list.length === 0) list.push("images/room-s-1.jpg"); while (list.length < 3) list.push(list[list.length - 1]); return list.slice(0, 3); }
function normalizePhoneToDigits(phone) { return String(phone || "").replace(/[^\d]/g, ""); }
function isUsableUrl(value) { if (!value || typeof value !== "string") return false; const trimmed = value.trim(); if (!trimmed || trimmed.includes("replace-me")) return false; try { new URL(trimmed, location.origin); return true; } catch (_) { return trimmed.startsWith("#"); } }
function resolveAction(action) { const fallbackHref = "#contact"; if (!action) return { href: fallbackHref, label: "", target: "", rel: "" }; if (action.href) { const href = action.href.trim(); const external = href.startsWith("http"); return { href, label: action.label || "", target: external ? "_blank" : "", rel: external ? "noopener noreferrer" : "" }; } if (action.type === "naver") { if (isUsableUrl(siteConfig.contact.naverUrl)) return { href: siteConfig.contact.naverUrl.trim(), label: action.label || "", target: "_blank", rel: "noopener noreferrer" }; return { href: fallbackHref, label: action.fallbackLabel || action.label || "", target: "", rel: "" }; } if (action.type === "email") return { href: `mailto:${siteConfig.contact.email}`, label: action.label || "", target: "", rel: "" }; if (action.type === "phone") return { href: `tel:${normalizePhoneToDigits(siteConfig.contact.phone)}`, label: action.label || "", target: "", rel: "" }; if (action.type === "whatsapp") { const phone = normalizePhoneToDigits(siteConfig.contact.whatsappNumber || siteConfig.contact.phone); const text = currentLang === "ko" ? encodeURIComponent("안녕하세요. 홈스테이드 서울 객실 가능 여부를 문의드립니다.") : encodeURIComponent("Hello, I would like to ask about room availability at Homestead Seoul."); return { href: `https://wa.me/${phone}?text=${text}`, label: action.label || "", target: "_blank", rel: "noopener noreferrer" }; } if (action.type === "kakao" && isUsableUrl(siteConfig.contact.kakaoUrl)) return { href: siteConfig.contact.kakaoUrl.trim(), label: action.label || "", target: "_blank", rel: "noopener noreferrer" }; return { href: fallbackHref, label: action.label || "", target: "", rel: "" }; }
function renderActionLink(action, className) { const resolved = resolveAction(action); const targetAttr = resolved.target ? ` target="${resolved.target}" rel="${resolved.rel}"` : ""; return `<a class="${className}" href="${escapeHtml(resolved.href)}"${targetAttr}>${escapeHtml(resolved.label)}</a>`; }
function renderSectionHead(eyebrow, title, desc) { return `<div class="section-head"><p class="section-eyebrow">${escapeHtml(eyebrow)}</p><h2 class="section-title">${escapeHtml(title)}</h2>${desc ? `<p class="section-desc">${escapeHtml(desc)}</p>` : ""}</div>`; }

function renderHero(copy) {
  const hero = copy.hero || {};
  const heroImages = normalizeHeroImages(siteConfig.media.heroImages);
  const slides = hero.carouselSlides || [];
  return `<section class="section reveal"><div class="section-shell hero-shell"><div class="hero-grid hero-grid-carousel"><div class="hero-copy"><span class="hero-kicker">${escapeHtml(hero.kicker)}</span><h1 class="hero-title">${escapeHtml(hero.title)}</h1>${hero.subtitle ? `<p class="hero-subtitle">${escapeHtml(hero.subtitle)}</p>` : ""}${(hero.chips || []).length ? `<div class="hero-chip-row">${(hero.chips || []).map((chip) => `<span class="hero-chip">${escapeHtml(chip)}</span>`).join("")}</div>` : ""}<div class="hero-cta">${renderActionLink(hero.primaryAction, "btn btn-primary")}${renderActionLink(hero.secondaryAction, "btn btn-secondary")}${renderActionLink(hero.tertiaryAction, "btn btn-ghost")}</div>${(hero.notes || []).length ? `<div class="hero-aside-note">${(hero.notes || []).map((note) => `<span>${escapeHtml(note)}</span>`).join("")}</div>` : ""}</div><div class="hero-carousel-card"><div class="hero-carousel-frame">${heroImages.map((src, index) => { const slide = slides[index] || {}; const title = slide.title || getBrandTitle(); const badge = slide.badge || ""; return `<div class="hero-slide${index === 0 ? " active" : ""}" data-hero-slide="${index}"><img src="${escapeHtml(src)}" alt="${escapeHtml(title)}"><div class="hero-slide-copy">${badge ? `<span class="hero-slide-badge">${escapeHtml(badge)}</span>` : ""}<strong>${escapeHtml(title)}</strong></div></div>`; }).join("")}</div><div class="hero-carousel-dots" role="tablist">${heroImages.map((_, index) => `<button type="button" class="hero-dot${index === 0 ? " active" : ""}" data-hero-dot="${index}" aria-label="Hero slide ${index + 1}"></button>`).join("")}</div></div></div></div></section>`;
}

function renderQuickFacts(copy) { if (!copy.quickFacts) return ""; return `<section id="quick-facts" class="section reveal"><div class="section-shell soft">${renderSectionHead(copy.quickFacts.eyebrow, copy.quickFacts.title, copy.quickFacts.desc)}<div class="summary-strip">${copy.quickFacts.items.map((item) => `<article class="summary-item"><span class="summary-label">${escapeHtml(item.label)}</span><strong class="summary-value">${escapeHtml(item.value)}</strong>${item.note ? `<span class="summary-note">${escapeHtml(item.note)}</span>` : ""}</article>`).join("")}</div></div></section>`; }
function renderConcept(copy) { if (!copy.concept) return ""; return `<section id="about" class="section reveal"><div class="section-shell">${renderSectionHead(copy.concept.eyebrow, copy.concept.title, copy.concept.desc)}<div class="concept-grid">${copy.concept.cards.map((card) => `<article class="concept-card"><h3>${escapeHtml(card.title)}</h3><p>${escapeHtml(card.copy)}</p></article>`).join("")}</div></div></section>`; }
function renderCollections(copy) { return `<section id="room-collections" class="section reveal"><div class="section-shell">${renderSectionHead(copy.collections.eyebrow, copy.collections.title, copy.collections.desc)}<div class="collection-grid">${(siteConfig.collections || []).map((collection) => { const title = currentLang === "ko" ? collection.titleKo : collection.titleEn; const stat = currentLang === "ko" ? collection.statKo : collection.statEn; const body = currentLang === "ko" ? collection.copyKo : collection.copyEn; const prefix = currentLang === "ko" ? "해당 호실" : "Rooms"; return `<article class="collection-card"><div class="collection-media"><img src="${escapeHtml(collection.image)}" alt="${escapeHtml(title)}"><span class="collection-stat">${escapeHtml(stat)}</span></div><div class="collection-body"><h3>${escapeHtml(title)}</h3><p class="collection-copy">${escapeHtml(body)}</p><ul class="collection-room-list"><li>${escapeHtml(`${prefix}: ${collection.rooms.join(" / ")}`)}</li></ul></div></article>`; }).join("")}</div></div></section>`; }
function renderInventory(copy) { return `<section class="section reveal"><div class="section-shell">${renderSectionHead(copy.inventory.eyebrow, copy.inventory.title, copy.inventory.desc)}<div class="inventory-toolbar"><p class="helper-copy">${escapeHtml(copy.inventory.helper)}</p><div class="filter-bar" role="tablist">${copy.inventory.filters.map((filter) => `<button type="button" class="filter-btn${activeRoomFilter === filter.id ? " active" : ""}" data-room-filter="${escapeHtml(filter.id)}">${escapeHtml(filter.label)}</button>`).join("")}</div></div><div class="room-grid">${(siteConfig.rooms || []).map((room) => { const hidden = activeRoomFilter !== "all" && !(room.filters || []).includes(activeRoomFilter); const tag = currentLang === "ko" ? room.tagKo : room.tagEn; const title = currentLang === "ko" ? room.titleKo : room.titleEn; const body = currentLang === "ko" ? room.copyKo : room.copyEn; const points = currentLang === "ko" ? room.pointsKo : room.pointsEn; const price = currentLang === "ko" ? room.priceKo : room.priceEn; return `<article class="room-card${hidden ? " is-hidden" : ""}"><div class="room-card-media"><img src="${escapeHtml(room.image)}" alt="${escapeHtml(title)}"></div><div class="room-card-body"><div class="room-card-top"><div class="room-card-title-wrap"><span class="room-card-tag">${escapeHtml(tag)}</span><h3 class="room-card-title">${escapeHtml(title)}</h3></div><span class="tier-pill">${escapeHtml(room.tier)}</span></div><p class="room-card-copy">${escapeHtml(body)}</p><div class="price-block"><p class="price-main">${escapeHtml(price)}</p></div><ul class="room-feature-list">${(points || []).map((point) => `<li>${escapeHtml(point)}</li>`).join("")}</ul><div class="room-card-actions">${renderActionLink({ href: "#contact", label: copy.inventory.primaryCta }, "btn btn-primary btn-compact")}${renderActionLink({ href: "#pricing", label: copy.inventory.secondaryCta }, "btn btn-secondary btn-compact")}</div></div></article>`; }).join("")}</div></div></section>`; }
function renderGallery(copy) { return `<section id="gallery" class="section reveal"><div class="section-shell soft">${renderSectionHead(copy.gallery.eyebrow, copy.gallery.title, copy.gallery.desc)}<div class="tier-gallery-grid">${(siteConfig.media.tierGallery || []).map((group) => { const title = currentLang === "ko" ? group.titleKo : group.titleEn; const badge = currentLang === "ko" ? group.badgeKo : group.badgeEn; const price = currentLang === "ko" ? group.priceKo : group.priceEn; const body = currentLang === "ko" ? group.descKo : group.descEn; return `<article class="tier-gallery-card"><div class="tier-gallery-head"><div>${badge ? `<span class="tier-gallery-badge">${escapeHtml(badge)}</span>` : ""}<h3>${escapeHtml(title)}</h3></div><strong class="tier-gallery-price">${escapeHtml(price)}</strong></div>${body ? `<p class="tier-gallery-copy">${escapeHtml(body)}</p>` : ""}<div class="tier-gallery-images">${(group.images || []).map((image) => { const caption = currentLang === "ko" ? image.captionKo : image.captionEn; return `<button type="button" class="gallery-item tier-gallery-item" data-gallery-src="${escapeHtml(image.src)}" data-gallery-alt="${escapeHtml(caption)}" data-gallery-caption="${escapeHtml(caption)}"><img src="${escapeHtml(image.src)}" alt="${escapeHtml(caption)}"><span class="visual-caption">${escapeHtml(caption)}</span></button>`; }).join("")}</div></article>`; }).join("")}</div></div></section>`; }
function renderIncluded(copy) { return `<section id="included" class="section reveal"><div class="section-shell">${renderSectionHead(copy.included.eyebrow, copy.included.title, copy.included.desc)}<div class="included-grid simple-included-grid">${copy.included.cards.map((card) => `<article class="amenity-card simple-amenity-card"><h3 class="amenity-title">${escapeHtml(card.title)}</h3><p class="amenity-desc">${escapeHtml(card.desc)}</p></article>`).join("")}</div></div></section>`; }
function renderPricing(copy) { return `<section id="pricing" class="section reveal"><div class="section-shell soft">${renderSectionHead(copy.pricing.eyebrow, copy.pricing.title, copy.pricing.desc)}<div class="pricing-layout"><div class="pricing-panel"><div class="pricing-simple-grid">${copy.pricing.rows.map((row) => `<article class="pricing-row simple-pricing-row"><div class="pricing-row-head"><strong>${escapeHtml(row.tier)}</strong><span class="price-label">${escapeHtml(row.rooms)}</span></div><div class="pricing-row-body"><div class="pricing-allin-grid"><div class="pricing-col"><span class="pricing-col-label">${escapeHtml(currentLang === "ko" ? "월 비용" : "Monthly price")}</span><span class="pricing-col-value">${escapeHtml(row.price)}</span></div><div class="pricing-col"><span class="pricing-col-label">${escapeHtml(currentLang === "ko" ? "보증금" : "Deposit")}</span><span class="pricing-col-value">${escapeHtml(row.deposit)}</span></div></div><span class="helper-copy">${escapeHtml(row.note)}</span></div></article>`).join("")}</div></div><aside class="pricing-note-card"><h3>${escapeHtml(copy.pricing.sideTitle)}</h3><p>${escapeHtml(copy.pricing.sideBody)}</p><ul class="pricing-note-list">${copy.pricing.notes.map((note) => `<li>${escapeHtml(note)}</li>`).join("")}</ul></aside></div></div></section>`; }
function renderProcess(copy) { if (!copy.process) return ""; return `<section id="move-in" class="section reveal"><div class="section-shell">${renderSectionHead(copy.process.eyebrow, copy.process.title, copy.process.desc)}<div class="process-grid">${copy.process.steps.map((step, index) => `<article class="step-card"><span class="step-index">${index + 1}</span><h3>${escapeHtml(step.title)}</h3><p class="step-copy">${escapeHtml(step.copy)}</p></article>`).join("")}</div></div></section>`; }
function renderLocation(copy) { return `<section id="location" class="section reveal"><div class="section-shell">${renderSectionHead(copy.location.eyebrow, copy.location.title, copy.location.desc)}<div class="location-grid"><div class="map-card"><iframe class="map-frame" title="${escapeHtml(currentLang === "ko" ? "홈스테이드 서울 위치" : "Homestead Seoul location")}" src="${escapeHtml(siteConfig.contact.mapEmbed)}" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div><aside class="location-card">${copy.location.sideTitle ? `<h3>${escapeHtml(copy.location.sideTitle)}</h3>` : ""}${copy.location.sideBody ? `<p>${escapeHtml(copy.location.sideBody)}</p>` : ""}<ul class="location-list">${copy.location.points.map((point) => `<li>${escapeHtml(point)}</li>`).join("")}</ul></aside></div></div></section>`; }
function renderFaq(copy) { return `<section id="faq" class="section reveal"><div class="section-shell soft">${renderSectionHead(copy.faq.eyebrow, copy.faq.title, "")}<div class="faq-list">${copy.faq.items.map((item) => `<details class="faq-item"><summary>${escapeHtml(item.q)}</summary><p>${escapeHtml(item.a)}</p></details>`).join("")}</div></div></section>`; }
function renderContact(copy) { const channelCard = (channel) => { const action = resolveAction({ type: channel.type, label: channel.label, fallbackLabel: channel.label }); const attrs = action.target ? ` target="${action.target}" rel="${action.rel}"` : ""; return `<a class="channel-card" href="${escapeHtml(action.href)}"${attrs}><div class="channel-title"><strong>${escapeHtml(channel.label)}</strong><span class="channel-badge">${escapeHtml(channel.type)}</span></div>${channel.hint ? `<p class="channel-hint">${escapeHtml(channel.hint)}</p>` : ""}</a>`; }; const submitLabel = shouldOpenDraftInsteadOfSending() ? (currentLang === "ko" ? "이메일 초안 열기" : "Open email draft") : copy.contact.form.submit; return `<section id="contact" class="section reveal"><div class="section-shell"><div class="contact-wrap"><div class="contact-intro">${renderSectionHead(copy.contact.eyebrow, copy.contact.title, copy.contact.message)}<div class="channel-grid">${copy.contact.channels.map(channelCard).join("")}</div></div><form id="inquiryForm" class="inquiry-form"><div class="field-grid"><div class="input-field"><label for="nameField">${escapeHtml(copy.contact.form.name)}</label><input id="nameField" name="name" type="text" maxlength="80" required></div><div class="input-field"><label for="contactField">${escapeHtml(copy.contact.form.contact)}</label><input id="contactField" name="contact" type="text" maxlength="120" required></div></div><div class="input-field"><label for="messageField">${escapeHtml(copy.contact.form.message)}</label><textarea id="messageField" name="message" maxlength="1200" placeholder="${escapeHtml(copy.contact.form.placeholder)}" required></textarea></div><label class="consent-row"><input type="checkbox" name="consent" required><span>${escapeHtml(copy.contact.form.consent)}</span></label><input type="hidden" name="language" value="${escapeHtml(currentLang)}"><button type="submit" class="btn btn-primary">${escapeHtml(submitLabel)}</button><p id="formStatus" class="form-status" role="status" aria-live="polite"></p></form></div></div></section>`; }

function renderPage() { const copy = getCurrentCopy(); const sections = { hero: renderHero(copy), quickFacts: renderQuickFacts(copy), concept: renderConcept(copy), collections: renderCollections(copy), inventory: renderInventory(copy), gallery: renderGallery(copy), included: renderIncluded(copy), pricing: renderPricing(copy), process: renderProcess(copy), location: renderLocation(copy), faq: renderFaq(copy), contact: renderContact(copy) }; document.getElementById("app").innerHTML = (copy.sections || []).map((key) => sections[key] || "").join(""); renderChrome(copy); bindInventoryFilters(); bindGalleryModal(); bindInquiryForm(); bindReveal(); bindDrawerLinks(); bindHeroCarousel(); applySeo(copy); }
function renderChrome(copy) { document.documentElement.lang = currentLang; document.getElementById("brandTitle").textContent = getBrandTitle(); document.getElementById("brandSubtitle").textContent = getBrandSubtitle(); document.getElementById("drawerTagline").textContent = getBrandSubtitle(); document.getElementById("footerBrand").textContent = getBrandTitle(); const footerCopy = document.getElementById("footerCopy"); const footerAddress = document.getElementById("footerAddress"); const footerSep = document.querySelector(".footer-sep"); footerCopy.textContent = copy.footer.copy || ""; footerCopy.hidden = !copy.footer.copy; footerAddress.textContent = copy.footer.address || ""; footerAddress.hidden = !copy.footer.address; if (footerSep) footerSep.hidden = !copy.footer.address; document.getElementById("desktopNav").innerHTML = copy.nav.map((item) => `<a href="${escapeHtml(item.href)}">${escapeHtml(item.label)}</a>`).join(""); document.getElementById("mobileNav").innerHTML = copy.nav.map((item) => `<a href="${escapeHtml(item.href)}">${escapeHtml(item.label)}</a>`).join(""); const hero = copy.hero || {}; const headerPrimary = resolveAction(hero.primaryAction); const headerCta = document.getElementById("headerPrimaryCta"); headerCta.textContent = headerPrimary.label; headerCta.href = headerPrimary.href; if (headerPrimary.target) { headerCta.target = headerPrimary.target; headerCta.rel = headerPrimary.rel; } else { headerCta.removeAttribute("target"); headerCta.removeAttribute("rel"); } document.getElementById("drawerCtas").innerHTML = renderActionLink(hero.primaryAction, "btn btn-primary") + renderActionLink(hero.secondaryAction, "btn btn-secondary"); document.getElementById("stickyMobileCta").innerHTML = `<div class="sticky-mobile-cta-inner">${copy.contact.mobileCtas.map((cta, index) => renderActionLink(cta, `btn ${index === 0 ? "btn-primary" : "btn-secondary"}`)).join("")}</div>`; document.getElementById("footerLinks").innerHTML = copy.footer.links.map((item) => `<a href="${escapeHtml(item.href)}">${escapeHtml(item.label)}</a>`).join(""); document.querySelectorAll("[data-lang-btn]").forEach((button) => button.classList.toggle("active", button.dataset.langBtn === currentLang)); }
function applySeo(copy) { document.title = copy.seo.title; document.getElementById("metaDescription").setAttribute("content", copy.seo.description); document.getElementById("ogTitle").setAttribute("content", copy.seo.ogTitle); document.getElementById("ogDescription").setAttribute("content", copy.seo.ogDescription); document.querySelector('meta[property="og:locale"]').setAttribute("content", copy.seo.locale); }
function bindInventoryFilters() { document.querySelectorAll("[data-room-filter]").forEach((button) => button.addEventListener("click", () => { activeRoomFilter = button.dataset.roomFilter || "all"; renderPage(); })); }
function openImageModal(src, alt, caption) { const modal = document.getElementById("imageModal"); document.getElementById("imageModalImg").src = src; document.getElementById("imageModalImg").alt = alt; document.getElementById("imageModalCaption").textContent = caption; modal.hidden = false; document.body.style.overflow = "hidden"; }
function closeImageModal() { const modal = document.getElementById("imageModal"); document.getElementById("imageModalImg").src = ""; document.getElementById("imageModalCaption").textContent = ""; modal.hidden = true; document.body.style.overflow = ""; }
function bindGalleryModal() { document.querySelectorAll("[data-gallery-src]").forEach((button) => button.addEventListener("click", () => openImageModal(button.dataset.gallerySrc || "", button.dataset.galleryAlt || "", button.dataset.galleryCaption || ""))); }
function stopHeroCarousel() { if (heroCarouselTimer) { clearInterval(heroCarouselTimer); heroCarouselTimer = null; } }
function setHeroSlide(index) { const slides = Array.from(document.querySelectorAll("[data-hero-slide]")); const dots = Array.from(document.querySelectorAll("[data-hero-dot]")); if (slides.length === 0) return; heroSlideIndex = index % slides.length; slides.forEach((slide, slideIndex) => slide.classList.toggle("active", slideIndex === heroSlideIndex)); dots.forEach((dot, dotIndex) => dot.classList.toggle("active", dotIndex === heroSlideIndex)); }
function bindHeroCarousel() { stopHeroCarousel(); const slides = Array.from(document.querySelectorAll("[data-hero-slide]")); const dots = Array.from(document.querySelectorAll("[data-hero-dot]")); if (slides.length === 0) return; heroSlideIndex = 0; setHeroSlide(0); dots.forEach((dot) => dot.addEventListener("click", () => setHeroSlide(Number(dot.dataset.heroDot || "0")))); if (slides.length < 2) return; heroCarouselTimer = window.setInterval(() => setHeroSlide(heroSlideIndex + 1), 5200); }
function setStatus(message, type = "") { const node = document.getElementById("formStatus"); if (!node) return; node.textContent = message; node.className = type ? `form-status ${type}` : "form-status"; }
function buildMailtoFallback(payload) { const subject = payload.language === "ko" ? "[홈스테이드 서울] 웹사이트 문의" : "[Homestead Seoul] Website inquiry"; const body = payload.language === "ko" ? `이름: ${payload.name}\n연락처: ${payload.contact}\n\n문의 내용:\n${payload.message}` : `Name: ${payload.name}\nContact: ${payload.contact}\n\nMessage:\n${payload.message}`; return `mailto:${siteConfig.contact.email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`; }
function buildGmailComposeFallback(payload) { const subject = payload.language === "ko" ? "[홈스테이드 서울] 웹사이트 문의" : "[Homestead Seoul] Website inquiry"; const body = payload.language === "ko" ? `이름: ${payload.name}\n연락처: ${payload.contact}\n\n문의 내용:\n${payload.message}` : `Name: ${payload.name}\nContact: ${payload.contact}\n\nMessage:\n${payload.message}`; return `https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(siteConfig.contact.email)}&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`; }
function shouldOpenDraftInsteadOfSending() { return location.hostname.endsWith("github.io"); }
function triggerInquiryFallback(payload) { const message = payload.language === "ko" ? "문의가 자동 전송되지는 않습니다. 새로 열린 이메일 초안을 확인한 뒤 직접 보내주세요." : "Your inquiry was not sent automatically. Please review the email draft that opened and press Send."; const composeUrl = buildGmailComposeFallback(payload); const popup = window.open(composeUrl, "_blank", "noopener"); if (!popup) window.location.href = buildMailtoFallback(payload); setStatus(message, "info"); }
async function handleInquirySubmit(event) { event.preventDefault(); const copy = getCurrentCopy(); const form = event.currentTarget; const data = new FormData(form); const payload = { name: String(data.get("name") || "").trim(), contact: String(data.get("contact") || "").trim(), message: String(data.get("message") || "").trim(), language: String(data.get("language") || currentLang), turnstileToken: String(data.get("turnstileToken") || "").trim() }; if (shouldOpenDraftInsteadOfSending()) { triggerInquiryFallback(payload); return; } setStatus(copy.contact.form.sending); try { const response = await fetch("/api/inquiry", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const contentType = response.headers.get("content-type") || ""; const result = contentType.includes("application/json") ? await response.json() : null; if (response.ok && result && result.ok) { form.reset(); setStatus(copy.contact.form.success, "success"); return; } if (response.status === 404 || response.status >= 500) { triggerInquiryFallback(payload); return; } setStatus((result && result.message) || copy.contact.form.error, "error"); } catch (_) { triggerInquiryFallback(payload); } }
function bindInquiryForm() { document.getElementById("inquiryForm")?.addEventListener("submit", handleInquirySubmit); }
function bindReveal() { const elements = document.querySelectorAll(".reveal"); const observer = new IntersectionObserver((entries) => { entries.forEach((entry) => { if (!entry.isIntersecting) return; entry.target.classList.add("show"); observer.unobserve(entry.target); }); }, { threshold: 0.14 }); elements.forEach((element) => observer.observe(element)); }
function openDrawer() { const drawer = document.getElementById("mobileDrawer"); const backdrop = document.getElementById("drawerBackdrop"); const menuBtn = document.getElementById("menuBtn"); lastFocusedElement = document.activeElement; drawer.classList.add("open"); drawer.setAttribute("aria-hidden", "false"); backdrop.hidden = false; menuBtn.setAttribute("aria-expanded", "true"); isDrawerOpen = true; }
function closeDrawer() { const drawer = document.getElementById("mobileDrawer"); const backdrop = document.getElementById("drawerBackdrop"); const menuBtn = document.getElementById("menuBtn"); drawer.classList.remove("open"); drawer.setAttribute("aria-hidden", "true"); backdrop.hidden = true; menuBtn.setAttribute("aria-expanded", "false"); isDrawerOpen = false; if (lastFocusedElement instanceof HTMLElement) lastFocusedElement.focus(); }
function bindDrawerLinks() { document.querySelectorAll("#mobileDrawer a").forEach((link) => link.addEventListener("click", closeDrawer)); }
function bindStaticChrome() { document.querySelectorAll("[data-lang-btn]").forEach((button) => button.addEventListener("click", () => { if (button.dataset.langBtn === currentLang) return; currentLang = button.dataset.langBtn; activeRoomFilter = "all"; localStorage.setItem("preferred_lang", currentLang); closeDrawer(); renderPage(); window.scrollTo({ top: 0, behavior: "smooth" }); })); document.getElementById("menuBtn").addEventListener("click", () => (isDrawerOpen ? closeDrawer() : openDrawer())); document.getElementById("drawerCloseBtn").addEventListener("click", closeDrawer); document.getElementById("drawerBackdrop").addEventListener("click", closeDrawer); document.getElementById("imageModalClose").addEventListener("click", closeImageModal); document.getElementById("imageModal").addEventListener("click", (event) => { if (event.target === document.getElementById("imageModal")) closeImageModal(); }); document.addEventListener("keydown", (event) => { if (event.key !== "Escape") return; if (!document.getElementById("imageModal").hidden) { closeImageModal(); return; } if (isDrawerOpen) closeDrawer(); }); }
function bindYear() { document.getElementById("year").textContent = String(new Date().getFullYear()); }
function loadLocalAdminOverrides() { try { const raw = localStorage.getItem(ADMIN_OVERRIDE_KEY); if (!raw) return; siteConfig = deepMerge(siteConfig, JSON.parse(raw)); } catch (_) {} }
async function loadServerAdminOverrides() { try { const response = await fetch("/api/site-config", { cache: "no-store" }); if (!response.ok) return false; const result = await response.json(); if (!result || !result.ok || !result.config || typeof result.config !== "object") return false; siteConfig = deepMerge(siteConfig, result.config); return true; } catch (_) { return false; } }

async function init() { const serverLoaded = await loadServerAdminOverrides(); if (!serverLoaded) loadLocalAdminOverrides(); bindStaticChrome(); bindYear(); renderPage(); }
init();
